# Generated by Django 3.0.7 on 2020-06-13 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Silabas',
            new_name='Silaba',
        ),
    ]
