# Generated by Django 3.0.7 on 2020-06-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200613_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silaba',
            name='palavra1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='silaba',
            name='palavra2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
