# Generated by Django 3.0.7 on 2020-06-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200618_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silaba',
            name='imagem1',
            field=models.ImageField(blank=True, null=True, upload_to='silabas'),
        ),
        migrations.AlterField(
            model_name='silaba',
            name='imagem2',
            field=models.ImageField(blank=True, null=True, upload_to='silabas'),
        ),
    ]
