# Generated by Django 3.0.7 on 2020-06-19 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_compartilhamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compartilhamento',
            options={'ordering': ('mes', 'ano')},
        ),
        migrations.AlterUniqueTogether(
            name='compartilhamento',
            unique_together={('mes', 'ano')},
        ),
    ]
