# Generated by Django 3.0.7 on 2020-06-23 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contato'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contato',
            new_name='Comentario',
        ),
    ]
