# Generated by Django 3.0.7 on 2020-06-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200623_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrica',
            name='sorteios',
            field=models.BigIntegerField(default=0),
        ),
    ]
