# Generated by Django 3.0.7 on 2020-06-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200624_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrica',
            name='email',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='facebook',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='telegram',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='twitter',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='whatsapp',
            field=models.BigIntegerField(default=0),
        ),
    ]
